#!/bin/bash

sudo apt update
sudo apt install gdisk

cp encuentra-pendrive.py /usr/local/bin
cp minino-traspasa32 /usr/local/bin/minino-traspasa
#cp -a refind /opt/
cp minino-traspasa.desktop /usr/local/share/applications/minino
