#!/bin/bash

sudo apt update
sudo apt install gdisk

cp encuentra-pendrive.py /usr/local/bin
cp minino-traspasa /usr/local/bin
cp -a refind /opt/
cp minino-traspasa.desktop /usr/local/share/applications/minino
