#!/bin/bash

sudo apt-get update
sudo apt-get install gdisk

cp encuentra-pendrive.py /usr/local/bin
cp minino-traspasa /usr/local/bin
cp -a refind /opt/
cp minino-traspasa.desktop /usr/local/share/applications/minino
